// hastas.js
// Each card: { name, meaning, description, category }
// Images: import them in your component, or use public/ paths if you add image files.
// For now, `image` is a placeholder filename — swap in your actual src/assets/ paths.

export const hastas = {
  asamyutha: [
    {
      name: "Pataka",
      meaning: "Flag",
      description: "Four fingers extended and joined, thumb bent across the palm.",
      category: "asamyutha",
      image: '/assets/asamyutha/pathaka.png', // replace with: import patakaImg from './assets/pataka.png'
    },
    {
      name: "Tripataka",
      meaning: "Three parts of a flag",
      description: "Pataka with the ring finger bent down.",
      category: "asamyutha",
      image: '/assets/asamyutha/tripathaka.png',
    },
    {
      name: "Ardhapataka",
      meaning: "Half flag",
      description: "Tripataka with the little finger also bent.",
      category: "asamyutha",
      image: '/assets/asamyutha/ardhapathaka.png',
    },
    {
      name: "Kartarimukha",
      meaning: "Scissors",
      description: "Index and little finger extended, middle and ring fingers bent, thumb bent.",
      category: "asamyutha",
      image: '/assets/asamyutha/kartari.png',
    },
    {
      name: "Mayura",
      meaning: "Peacock",
      description: "Little finger raised, thumb touching the index fingertip, other three extended.",
      category: "asamyutha",
      image: '/assets/asamyutha/mayura.png',
    },
    {
      name: "Ardhachandra",
      meaning: "Half moon",
      description: "Pataka with the thumb extended outward.",
      category: "asamyutha",
      image: '/assets/asamyutha/ardachandra.png',
    },
    {
      name: "Arala",
      meaning: "Bent",
      description: "Pataka with the index finger bent back.",
      category: "asamyutha",
      image: '/assets/asamyutha/arala.png',
    },
    {
      name: "Shukatunda",
      meaning: "Parrot's beak",
      description: "Tripataka with the index finger bent to touch the thumb.",
      category: "asamyutha",
      image: '/assets/asamyutha/shukhathunda.png',
    },
    {
      name: "Mushti",
      meaning: "Fist",
      description: "All fingers closed into a fist, thumb resting on the middle finger.",
      category: "asamyutha",
      image: '/assets/asamyutha/mushti.png',
    },
    {
      name: "Shikhara",
      meaning: "Peak / Temple spire",
      description: "Mushti with the thumb raised straight up.",
      category: "asamyutha",
      image: '/assets/asamyutha/shikara.png',
    },
    {
      name: "Kapittha",
      meaning: "Wood-apple",
      description: "Shikhara with the index finger curled to touch the thumb.",
      category: "asamyutha",
      image: '/assets/asamyutha/kapitha.png',
    },
    {
      name: "Katakamukha",
      meaning: "Opening in a bracelet",
      description: "Index, middle fingers extended and slightly separated; ring, little fingers bent; thumb extended.",
      category: "asamyutha",
      image: '/assets/asamyutha/katakamukha.png',
    },
    {
      name: "Suchi",
      meaning: "Needle",
      description: "Mushti with the index finger pointing straight up.",
      category: "asamyutha",
      image: '/assets/asamyutha/soochi.png',
    },
    {
      name: "Chandrakala",
      meaning: "Crescent moon",
      description: "Ardhachandra with only the little finger extended.",
      category: "asamyutha",
      image: '/assets/asamyutha/chandrakala.png',
    },
    {
      name: "Padmakosha",
      meaning: "Lotus bud",
      description: "All fingers spread and slightly curved, like a blooming lotus.",
      category: "asamyutha",
      image: '/assets/asamyutha/padmakosha.png',
    },
    {
      name: "Sarpashirsha",
      meaning: "Snake's head",
      description: "All fingers extended and joined, wrist bent so fingers point downward.",
      category: "asamyutha",
      image: '/assets/asamyutha/sarpasirsha.png',
    },
    {
      name: "Mrigashirsha",
      meaning: "Deer's head",
      description: "Little and index fingers raised; middle, ring bent; thumb touching ring fingertip.",
      category: "asamyutha",
      image: '/assets/asamyutha/mrigasirsha.png',
    },
    {
      name: "Simhamukha",
      meaning: "Lion's face",
      description: "Mrigashirsha with the index finger also bent, leaving only the little finger up.",
      category: "asamyutha",
      image: '/assets/asamyutha/simhamukha.png',
    },
    {
      name: "Kangula",
      meaning: "Bell",
      description: "Katakamukha with the thumb bent inward.",
      category: "asamyutha",
      image: '/assets/asamyutha/kangula.png',
    },
    {
      name: "Alapadma",
      meaning: "Fully bloomed lotus",
      description: "All five fingers spread wide, palm facing outward.",
      category: "asamyutha",
      image: '/assets/asamyutha/alapadma.png',
    },
    {
      name: "Chatura",
      meaning: "Clever / Square",
      description: "Four fingers together and horizontal, thumb bent against the palm.",
      category: "asamyutha",
      image: '/assets/asamyutha/chaturo.png',
    },
    {
      name: "Bhramara",
      meaning: "Bee",
      description: "Index finger curled to touch the thumb; middle finger crosses over index; ring and little extended.",
      category: "asamyutha",
      image: '/assets/asamyutha/bramara.png',
    },
    {
      name: "Hamsasya",
      meaning: "Swan's beak",
      description: "Thumb, index, and middle fingertips pinched together; ring and little extended.",
      category: "asamyutha",
      image: '/assets/asamyutha/hamsasyo.png',
    },
    {
      name: "Hamsapaksha",
      meaning: "Swan's wing",
      description: "All five fingers extended, slightly fanned, wrist relaxed.",
      category: "asamyutha",
      image: '/assets/asamyutha/hamsapaksha.png',
    },
    {
      name: "Sandamsha",
      meaning: "Pincers / Tongs",
      description: "Index and middle fingertips pinch together, other fingers closed.",
      category: "asamyutha",
      image: '/assets/asamyutha/samdamsho.png',
    },
    {
      name: "Mukula",
      meaning: "Flower bud",
      description: "All five fingertips joined and pointing upward, like a closed bud.",
      category: "asamyutha",
      image: '/assets/asamyutha/mukula.png',
    },
    {
      name: "Tamrachuda",
      meaning: "Rooster",
      description: "Tripataka with the thumb extended and index finger curved slightly.",
      category: "asamyutha",
      image: '/assets/asamyutha/tamrachooda.png',
    },
    {
      name: "Trishula",
      meaning: "Trident",
      description: "Index, middle, and ring fingers extended and separated; little and thumb closed.",
      category: "asamyutha",
      image: '/assets/asamyutha/pathaka.png',
    },
  ],

  samyutha: [
    {
      name: "Anjali",
      meaning: "Salutation / Prayer",
      description: "Both palms pressed together flat at chest level.",
      category: "samyutha",
      image: '/assets/samyutha/anjali.png',
    },
    {
      name: "Kapota",
      meaning: "Dove / Pigeon",
      description: "Anjali with thumbs crossed over each other.",
      category: "samyutha",
      image: '/assets/samyutha/kapota.png',
    },
    {
      name: "Karkata",
      meaning: "Crab",
      description: "Both hands interlocked with fingers interleaved and curled.",
      category: "samyutha",
      image: '/assets/samyutha/kartaka.png',
    },
    {
      name: "Swastika",
      meaning: "Auspicious cross",
      description: "Both wrists crossed, hands in Pataka with fingers pointing outward.",
      category: "samyutha",
      image: '/assets/samyutha/swastika.png',
    },
    {
      name: "Dola",
      meaning: "Swinging / Swing",
      description: "Both hands in Pataka hanging loosely at the sides, swinging gently.",
      category: "samyutha",
      image: '/assets/samyutha/dola.png',
    },
    {
      name: "Pushpaputa",
      meaning: "Hollow for holding flowers",
      description: "Both hands cupped together side by side, palms facing upward.",
      category: "samyutha",
      image: '/assets/samyutha/pushpaputa.png',
    },
    {
      name: "Utsanga",
      meaning: "Embrace",
      description: "Each hand touches the opposite shoulder, arms crossed at the chest.",
      category: "samyutha",
      image: '/assets/samyutha/utsanga.png',
    },
    {
      name: "Shivalinga",
      meaning: "Symbol of Shiva",
      description: "Left hand in Ardhachandra facing up; right hand in Shikhara placed on top.",
      category: "samyutha",
      image: '/assets/samyutha/shivalinga.png',
    },
    {
      name: "Katakavardhana",
      meaning: "Increasing prosperity",
      description: "Both hands in Katakamukha, one above the other, rotating in an upward spiral.",
      category: "samyutha",
      image: '/assets/samyutha/katakavardana.png',
    },
    {
      name: "Kartariswastika",
      meaning: "Crossed scissors",
      description: "Both hands in Kartarimukha with wrists crossed in front.",
      category: "samyutha",
      image: '/assets/samyutha/kartariswastika.png',
    },
    {
      name: "Shakata",
      meaning: "Cart / Wagon",
      description: "Both hands in Bhramara, thumbs touching, held in front of the chest.",
      category: "samyutha",
      image: '/assets/samyutha/shakatam.png',
    },
    {
      name: "Shankha",
      meaning: "Conch shell",
      description: "Left thumb grasped by right fingers; right thumb raised; other fingers wrap the left fist.",
      category: "samyutha",
      image: '/assets/samyutha/shanka.png',
    },
    {
      name: "Chakra",
      meaning: "Wheel / Discus",
      description: "Both hands in Ardhachandra, thumbs touching, held horizontally like a spinning disc.",
      category: "samyutha",
      image: '/assets/samyutha/chakra.png',
    },
    {
      name: "Samputa",
      meaning: "Box / Container",
      description: "Both hands cupped and joined to form a hollow sphere.",
      category: "samyutha",
      image: '/assets/samyutha/samputa.png',
    },
    {
      name: "Pasha",
      meaning: "Noose / Bond",
      description: "Both hands in Sandamsha, linked together like interlocking rings.",
      category: "samyutha",
      image: '/assets/samyutha/pasha.png',
    },
    {
      name: "Kilaka",
      meaning: "Bond / Pin",
      description: "Both hands in Mushti with little fingers hooked into each other.",
      category: "samyutha",
      image: '/assets/samyutha/kilakau.png',
    },
    {
      name: "Matsya",
      meaning: "Fish",
      description: "Right hand rests flat on the back of the left hand; right thumb extended as a fin.",
      category: "samyutha",
      image: '/assets/samyutha/matsya.png',
    },
    {
      name: "Kurma",
      meaning: "Tortoise",
      description: "Both hands in Arala, backs pressed together with fingers interlocked downward.",
      category: "samyutha",
      image: '/assets/samyutha/kurma.png',
    },
    {
      name: "Varaha",
      meaning: "Boar",
      description: "Right hand in Mrigashirsha placed over left hand in Sarpashirsha.",
      category: "samyutha",
      image: '/assets/samyutha/varaha.png',
    },
    {
      name: "Garuda",
      meaning: "Eagle (divine bird of Vishnu)",
      description: "Both thumbs interlocked; palms facing outward; fingers spread to form wings.",
      category: "samyutha",
      image: '/assets/samyutha/garudo.png',
    },
    {
      name: "Nagabandha",
      meaning: "Entwined serpents",
      description: "Both hands in Sarpashirsha, wrists crossed and twined like coiling snakes.",
      category: "samyutha",
      image: '/assets/samyutha/nagabanda.png',
    },
    {
      name: "Khatva",
      meaning: "Cot / Bedstead",
      description: "Both hands in Mushti, little fingers hooked and hands held horizontally.",
      category: "samyutha",
      image: '/assets/samyutha/katva.png',
    },
    {
      name: "Bherunda",
      meaning: "A pair of birds (twin bird of mythology)",
      description: "Both hands in Kapittha placed symmetrically side by side at chest level.",
      category: "samyutha",
      image: '/assets/samyutha/berunda.png',
    },
    {
      name: "Avahitha",
      meaning: "open, welcoming",
      description: "Both hands in alapadma placed crossed at chest level.",
      category: "samyutha",
      image: '/assets/samyutha/avahita.png',
    }
  ],
};

// Viniyoga (uses) for Pataka — extend this pattern for a full viniyoga database
export const pataka_viniyoga = [
  "The beginning of a dance",
  "Clouds",
  "A forest",
  "River",
  "Night",
  "Waving / fanning",
  "Requesting silence",
  "Blessing",
  "A horse",
  "Entering water",
];